// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for about me documents */
interface AboutMeDocumentData {
    /**
     * aboutMe field in *about me*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_me.aboutme
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    aboutme: prismicT.KeyTextField;
    /**
     * socialMedia field in *about me*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: about_me.socialmedia[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    socialmedia: prismicT.GroupField<Simplify<AboutMeDocumentDataSocialmediaItem>>;
    /**
     * phoneNumber field in *about me*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_me.phonenumber
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phonenumber: prismicT.KeyTextField;
    /**
     * whatsAppNumber field in *about me*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_me.whatsappnumber
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    whatsappnumber: prismicT.KeyTextField;
    /**
     * Email field in *about me*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_me.email
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email: prismicT.KeyTextField;
    /**
     * Name field in *about me*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_me.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * avatar field in *about me*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about_me.avatar
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    avatar: prismicT.ImageField<never>;
}
/**
 * Item in about me → socialMedia
 *
 */
export interface AboutMeDocumentDataSocialmediaItem {
    /**
     * facebook field in *about me → socialMedia*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: about_me.socialmedia[].facebook
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    facebook: prismicT.LinkField;
    /**
     * linkedIn field in *about me → socialMedia*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: about_me.socialmedia[].linkedin
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    linkedin: prismicT.LinkField;
    /**
     * Github field in *about me → socialMedia*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: about_me.socialmedia[].github
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    github: prismicT.LinkField;
}
/**
 * about me document from Prismic
 *
 * - **API ID**: `about_me`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutMeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<AboutMeDocumentData>, "about_me", Lang>;
/** Content for Education documents */
interface EducationDocumentData {
    /**
     * course field in *Education*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: education.course
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    course: prismicT.KeyTextField;
    /**
     * school field in *Education*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: education.school
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    school: prismicT.KeyTextField;
    /**
     * start field in *Education*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: education.start
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    start: prismicT.DateField;
    /**
     * end field in *Education*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: education.end
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    end: prismicT.DateField;
}
/**
 * Education document from Prismic
 *
 * - **API ID**: `education`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EducationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<EducationDocumentData>, "education", Lang>;
/** Content for Projects documents */
interface ProjectsDocumentData {
    /**
     * image field in *Projects*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Description field in *Projects*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * codeLink field in *Projects*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.codelink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    codelink: prismicT.LinkField;
    /**
     * previewLink field in *Projects*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.previewlink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    previewlink: prismicT.LinkField;
    /**
     * title field in *Projects*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * stack field in *Projects*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.stack
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    stack: prismicT.KeyTextField;
}
/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjectsDocumentData>, "projects", Lang>;
/** Content for skills documents */
interface SkillsDocumentData {
    /**
     * icon field in *skills*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: skills.icon
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismicT.ImageField<never>;
    /**
     * skillName field in *skills*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: skills.skillname
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    skillname: prismicT.KeyTextField;
    /**
     * skillStatus field in *skills*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: skills.skillstatus
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    skillstatus: prismicT.NumberField;
}
/**
 * skills document from Prismic
 *
 * - **API ID**: `skills`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<SkillsDocumentData>, "skills", Lang>;
/** Content for Work Experience documents */
interface WorkExperienceDocumentData {
    /**
     * role field in *Work Experience*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work_experience.role
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    role: prismicT.KeyTextField;
    /**
     * organization field in *Work Experience*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work_experience.organization
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    organization: prismicT.KeyTextField;
    /**
     * start field in *Work Experience*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: work_experience.start
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    start: prismicT.DateField;
    /**
     * end field in *Work Experience*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: work_experience.end
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    end: prismicT.DateField;
    /**
     * type field in *Work Experience*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work_experience.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    type: prismicT.KeyTextField;
}
/**
 * Work Experience document from Prismic
 *
 * - **API ID**: `work_experience`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkExperienceDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<WorkExperienceDocumentData>, "work_experience", Lang>;
export type AllDocumentTypes = AboutMeDocument | EducationDocument | ProjectsDocument | SkillsDocument | WorkExperienceDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AboutMeDocumentData, AboutMeDocumentDataSocialmediaItem, AboutMeDocument, EducationDocumentData, EducationDocument, ProjectsDocumentData, ProjectsDocument, SkillsDocumentData, SkillsDocument, WorkExperienceDocumentData, WorkExperienceDocument, AllDocumentTypes };
    }
}
